# Generated by Django 5.1.5 on 2025-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="phone_number",
            field=models.CharField(default=9842169708, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
    ]
