# Generated by Django 5.1.5 on 2025-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
