# Generated by Django 5.1.5 on 2025-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
