# Generated by Django 5.1.5 on 2025-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0010_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
