# Generated by Django 5.1.5 on 2025-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0011_alter_payment_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
