# Generated by Django 5.1.5 on 2025-04-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0012_vehicle_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
