# Generated by Django 5.1.5 on 2025-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0013_vehicle_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="license_document",
            field=models.FileField(
                blank=True,
                default="default_license_document.pdf",
                upload_to="documents/",
            ),
            preserve_default=False,
        ),
    ]
