name: front
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 #

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.5.1
  flutter_local_notifications: ^15.1.0
  workmanager: ^0.5.2

  image_picker: ^0.8.7+3
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git

  http: ^0.13.5
  dio: ^5.8.0+1
  url_launcher: ^6.1.10

  jwt_decoder: ^2.0.1
  flutter_plugin_android_lifecycle: ^2.0.18
  another_flushbar: ^1.12.30
  dropdown_search: ^6.0.2
dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
